spring.application.name=booking-service
server.port=${PORT:8083}

# ===== MySQL Database Connection =====
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/smartlab_bookings?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Rubitha123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== Register to Eureka =====
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# ===== Feign uses Apache HttpClient5 (proper PATCH support) =====
spring.cloud.openfeign.httpclient.hc5.enabled=true
